development:
  adapter: postgresql
  database: the_future_are_us_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: the_future_are_us_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: the_future_are_us_database_production
  pool: 5
  timeout: 5000