development:
  adapter: postgresql
  database: tfau_database_development
  host: localhost
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: tfau_database_test
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  database: tfau_database_production
  pool: 5
  timeout: 5000