# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600f2f547220aa0a4e2c6cd0dd54c6542ce3165b8dda7082854b0de5774081836d15f412409ebe3fc0618c850b3794607119dc55b89608efc29129ba4a69dca1

  stripe_publishable_key: pk_test_6QXEghCfp7v2mmhC2VeNK85b
  stripe_secret_key: sk_test_swc2J27zK6XbHDYGyTd2lO4h

test:
  secret_key_base: 8f1d232aabbfbbcdc0b2c4e2916c335665dc088b7ca13a950bfa870c4be77a0829e65d48f8044d723b8ac3e913f9529ae6cf1337bf4805bdb418b0136f58fed7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']